### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by Initiale** [simpligility/ksoap2-android#100]
when i call web service dump object contains text "Bad Request"

here is the code;
`` SoapObject request = new SoapObject(NAMESPACE, prms[0].MethodName);
            for (PropertyInfo pi : prms[0].Params) {
                request.addProperty(pi.name, pi.getValue());
            }
            SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(SoapEnvelope.VER12);
            envelope.setOutputSoapObject(request);
            envelope.env = "http://schemas.xmlsoap.org/soap/envelope/";

```
        envelope.dotNet = true;
        HttpTransportSE androidHttpTransport = new HttpTransportSE(URL);

        androidHttpTransport.setXmlVersionTag("<?xml version=\"1.0\" encoding=\"UTF-8\"?>");
        try {

            androidHttpTransport.debug = true;
            SOAP_ACTION1 += prms[0].MethodName;
            androidHttpTransport.call(SOAP_ACTION1, envelope);``
```

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
