### ISSUE TITLE
2 way ssl soap request with ksoap android - connection closed by peer

### ISSUE THREAD

**Issue by kshkrao3** [simpligility/ksoap2-android#101]
I have the below code to perform `2-way SSL` requests with `ksoap2`.

```
private static String callSOAPServer(String methodName,HashMap<String, String> parameter) throws IOException, UnrecoverableKeyException, CertificateException, NoSuchAlgorithmException, KeyStoreException, KeyManagementException {
    String response = null;
    METHOD_NAME=methodName;
    SoapObject request = new SoapObject(NAMESPACE, METHOD_NAME);
    TLSSocketFactory socketFactory=new TLSSocketFactory();
    SoapSerializationEnvelope envelope = new SoapSerializationEnvelope(SoapEnvelope.VER12);
    PropertyInfo pi = new PropertyInfo();
    pi.setName("des");
    pi.setValue(parameter.get("des"));
    request.addProperty(pi);

    envelope.bodyOut= request;

    HttpsTransportSE httpsTransportSE=new KeepAliveHttpsTransportSE(HOST,PORT,SERVICE,500000);
   ((HttpsServiceConnectionSE) httpsTransportSE.getServiceConnection()).setSSLSocketFactory(socketFactory);

    try {
        httpsTransportSE.call(NAMESPACE+METHOD_NAME, envelope);
        SoapPrimitive resp = (SoapPrimitive)envelope.getResponse();
        response=resp.toString();
    } catch (Exception e) {

        e.printStackTrace();
    }
    return response;
}
```

Now this returns **connection closed by peer** exception, which means certificates has not been sent with request. I had a feeling that `((HttpsServiceConnectionSE) httpsTransportSE.getServiceConnection()).setSSLSocketFactory(socketFactory);` should set the `SSLSocketFactory` to the request, but it doesn't.

When I dig deep, it is noticed that `httpsTransportSE.call()`  method, it internally calls `HttpTransportSE`'s call method, since`HttpsTransportSE` class is extended with `HttpTransportSE`. But when debugged, there isn't any `SSLSocketFactory` context attached with the request.

How this should be working? Am I assuming something wrong here? How am I actually supposed to attach my `socketFactory` to the `httpsTransportSE`? Hope to get some help.

Here is the detailed **[SO Question link](http://stackoverflow.com/questions/39652966/2-way-ssl-soap-request-with-ksoap-android-connection-closed-by-peer)**

**Comment by Giestas** [comment]
I have the same problem when the android version is > 7.0

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
