### ISSUE TITLE
http basic authenticate

### ISSUE THREAD

**Issue by dujuejue** [simpligility/ksoap2-android#103]
I can not pass the basic authenticate,and I do not know the head ,but i know the username and password,how can i set the defaultauthenticate

**Comment by robocik** [comment]
Have you tried this: http://stackoverflow.com/a/7576428/1109383 ?

**Comment by dujuejue** [comment]
thank you,i also found it ,but it don't do well

**Comment by prodigy007** [comment]
@dujuejue 
I also tormented for a long time. Finally I managed to chat right now that's guide -  http://stackoverflow.com/a/5614243
>>>soapEnvelope.headerOut = new Element[1];
this - > SoapSerializationEnvelope envelope
NAMESPACE  this  -> http://tempuri.org/

my code=>
 public Element buildAuthHeader() {
        Element h = new Element().createElement(NAMESPACE, "AuthHeader");
        Element username = new Element().createElement(NAMESPACE, "Username");
        username.addChild(Node.TEXT, "test");
        h.addChild(Node.ELEMENT, username);
       // Element pass = new Element().createElement(NAMESPACE, "pass");
      //  pass.addChild(Node.TEXT, pass);
      //  h.addChild(Node.ELEMENT, pass);
        return h;

In VS C#
	public class AuthHeader : SoapHeader
	{
		public string Username;
		//public string Password;
	}

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
