### ISSUE TITLE
How to get a .jar?

### ISSUE THREAD

**Issue by prodigy007** [simpligility/ksoap2-android#105]
I want to get the latest release .jar
3.6.2
but I have no idea how to build.....

**Comment by Kisty** [comment]
What sort of project do you have? Do you have a build.gradle file? If so then use in your dependencies section: 
`compile 'com.google.code.ksoap2-android:ksoap2-android:3.6.2'`

**Comment by prodigy007** [comment]
You mean to specify a folder in android studio instead .jar file?
In the evening, I try, if you have understood correctly. (my English is bad)

**Comment by Kisty** [comment]
What I mean is in your project folder, you should see an app folder, inside
that, you should see a build.gradle file. In that file, you should see a

```
dependencies {
    compile ...
}
```

Add the line I said before in there.

Hope this helps!

**Comment by mosabua** [comment]
And you need to add the repository to Gradle.

http://simpligility.github.io/ksoap2-android/getting-started.html

**Comment by prodigy007** [comment]
https://oss.sonatype.org/content/repositories/ksoap2-android-releases/com/google/code/ksoap2-android/ksoap2-android-assembly/
