### ISSUE TITLE
java.io.EOFException : ReadasciiLine

### ISSUE THREAD

**Issue by benoffi7** [simpligility/ksoap2-android#106]
Posted on Oct 2, 2014 by Grumpy Lion
This occurs frequently on newer Android due to bug in HTTPTransportSE. Also reported here: http://stackoverflow.com/questions/15411213/android-httpsurlconnection-eofexception

To Fix: Add line

connection.setRequestProperty("Connection", "close");

in HttpTransportSE.java around line 173, i.e. after calling ServiceConnection connection = getServiceConnection() This is in module ksoap2-jse in org.ksoap2.transport

**Comment by benoffi7** [comment]
https://code.google.com/archive/p/ksoap2-android/issues/207

**Comment by benoffi7** [comment]
https://code.google.com/archive/p/ksoap2-android/issues/199

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
