### ISSUE TITLE
How to solve?

### ISSUE THREAD

**Issue by DougZeng** [simpligility/ksoap2-android#109]
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <soapenv:Header/>
   <soapenv:Body>
      <tem:UploadStoreOrderData>
         <tem:objDS>
            <xs:schema id="_x0032_0170421144049" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
               <xs:element name="_x0032_0170421144049" msdata:IsDataSet="true" msdata:Locale="en-US">
                  <xs:complexType>
                     <xs:choice minOccurs="0" maxOccurs="unbounded">
                        <xs:element name="Info">
                           <xs:complexType>
                              <xs:sequence>
                                 <xs:element name="ORDER_DATE" type="xs:string" minOccurs="0"/>
                                 <xs:element name="ABI_ARTICLE_ID" type="xs:string" minOccurs="0"/>
                                 <xs:element name="PO_BATCH_QTY" type="xs:string" minOccurs="0"/>
                                 <xs:element name="INPUT_DATE" type="xs:string" minOccurs="0"/>
                              </xs:sequence>
                           </xs:complexType>
                        </xs:element>
                     </xs:choice>
                  </xs:complexType>
               </xs:element>
            </xs:schema>
            <diffgr:diffgram xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" xmlns:diffgr="urn:schemas-microsoft-com:xml-diffgram-v1">
               <_x0032_0170421144049 xmlns="">
                  <Info diffgr:id="Info1" msdata:rowOrder="0" diffgr:hasChanges="inserted">
                     <ORDER_DATE>20170422</ORDER_DATE>
                     <ABI_ARTICLE_ID>11010405</ABI_ARTICLE_ID>
                     <MIN_PO_BATCH_QTY>1</MIN_PO_BATCH_QTY>
                     <MAX_PO_BATCH_QTY>3</MAX_PO_BATCH_QTY>
                  </Info>
                  <Info diffgr:id="Info2" msdata:rowOrder="1" diffgr:hasChanges="inserted">
                     <ORDER_DATE>20170422</ORDER_DATE>
                     <ABI_ARTICLE_ID>11020001</ABI_ARTICLE_ID>
                     <MIN_PO_BATCH_QTY>1</MIN_PO_BATCH_QTY>
                     <MAX_PO_BATCH_QTY>999</MAX_PO_BATCH_QTY>
                  </Info>
               </_x0032_0170421144049>
            </diffgr:diffgram>
         </tem:objDS>
         <tem:strFileName>OrderInfo_31301701318557_20170429175900</tem:strFileName>
      </tem:UploadStoreOrderData>
   </soapenv:Body>
</soapenv:Envelope>
Above is a webservice request.
How to make a soapobject request like this in android?

**Comment by robocik** [comment]
Your web service returns .NET Framework DataSet object which is not supported by other platforms. Of course you can try create soapobject for it but this will be quite hard task. In our EasyWsdl.com generator we have a support for sending/retrieving DataSet object to Android but we have created a special parser for this job. So maybe the easiest solution would be to use the generator

**Comment by Kisty** [comment]
Yeah, definitely use a code generator, not by hand. We used www.wsdl2code.com

**Comment by apples398** [comment]
Really? So can you give me a example how to use?

**Comment by Kisty** [comment]
You need to click the link and follow the website instructions. It'll generate a bunch of code for you and a way to get data as java objects. I think you just need to tell where the WSDL file is on the server.

**Comment by apples398** [comment]
My url is in local.
Please Select A Valid Wsdl File?
Where is the wsdl file? Or how to get the wsdl file?

**Comment by Kisty** [comment]
What's the server you're communicating to? Is it a Windows server?

**Comment by apples398** [comment]
Yes

**Comment by Kisty** [comment]
OK. How did you get the xml that you gave in the first place? Do you have a
URL ending in .wsdl?

**Comment by apples398** [comment]
Yes  I open the URL ending in .wsdl and save it as document xml.

**Comment by Kisty** [comment]
Ok. Instead of giving the wsdl file locally, go to www.wsdl2code.com and
enter in the url to the WSDL file.

**Comment by apples398** [comment]
I tried .But the url is in my local.

**Comment by apples398** [comment]
It can not conneting to .

**Comment by Kisty** [comment]
Try clicking on the file button, then click on "Choose file" to select your local file.

**Comment by apples398** [comment]
I try the SoapUI save in a xml file .It still tell me Please Select A Valid Wsdl File.

**Comment by Kisty** [comment]
What's the url to download the XML?

**Comment by apples398** [comment]
It's a local service.

**Comment by Kisty** [comment]
Ah right. What's the WSDL file? Not the XML.

**Comment by robocik** [comment]
If your Web service is local then if you would like to use [EasyWSDL.com](http://EasyWSDL.com) generator, you can install Android Studio plugin for [EASYWSDL generator](https://plugins.jetbrains.com/plugin/7751-easywsdl-generator). Using this plugin you should be able to generate classes from your local Web service.
Please ensure to select Enable DataSet support option (support for DataSet requires license for additional library. If you are interested, please contact with easywsdl.com support)

**Comment by apples398** [comment]
I tried the Android Studio plugin for Easywsdl generator.But It's a Standard.So how to get the Premium plugin?

**Comment by apples398** [comment]
Result:
Total Generated Classes: 3
Total Generated Methods: 10
Time you've saved: 6.5 hours

Warnings: 
Wsdl2Code Don't Support DataSet Variables , in class 
Wsdl2Code Don't Support XmlNode Variables , in class 
The Wsdl2Code Engine Don't Support byref Variables , in class 
Wsdl2Code Don't Support String& Variables , in class

**Comment by Kisty** [comment]
Hmm, I think @robocik said you have dataset variables, but easywsdl does. I'd recommend you pay for the premium package so you can get those DataSet variables. Perhaps get the 30 day or larger package so you can use again if the server changes. It'll be money well spent!
