### ISSUE TITLE
wsdl2ksoap2-android linking to empty google code page

### ISSUE THREAD

**Issue by TheCodingPianoman** [simpligility/ksoap2-android#113]
Trying to use ksoap2 with a current android project, I came to the point where I have to generate ksoap2 java code for android by using the wsdl2ksoap2-android script. But the linked page at your [landing page](http://simpligility.github.io/ksoap2-android/getting-started.html) links to this [page](https://code.google.com/p/wsdl2ksoap2-android/) at google code. The Download link just gives me a 401 with following message:

> 401: Anonymous users does not have storage.objects.get access to object google-code-archive/v2/code.google.com/wsdl2ksoap2-android/downloads-page-1.json.

**Comment by Kisty** [comment]
Try this site instead. It's what I used. Just remove the code you don't need once you've got it working as it generates more code than needed.

http://www.wsdl2code.com/pages/home.aspx

It is true, perhaps the [home page to the project](https://github.com/simpligility/ksoap2-android/issues/113) needs the link to be removed, @mosabua?
