### ISSUE TITLE
addProperty

### ISSUE THREAD

**Issue by ghost** [simpligility/ksoap2-android#116]
SoapObject inseriranimal = new SoapObject(namespace, inserir);
			SoapObject pet = new SoapObject(namespace, "a");
			pet.addProperty("id", a.getId()); 
			pet.addProperty("tipo", a.getTipo());
			pet.addProperty("nome", a.getNome());
// como eu coloco um objeto usuario aqui para pegar o id e atribuir junto com essa requisição para o web service ?
			inseriranimal.addSoapObject(pet);

**Comment by mosabua** [comment]
?
