### ISSUE TITLE
Error: java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by zipswich** [simpligility/ksoap2-android#122]
This error frequently occurs on Android emulators when HttpTransportSE.call() is executed:

> cause = {java.net.ProtocolException@8112} "java.net.ProtocolException: unexpected end of stream"
>  backtrace = {java.lang.Object[10]@8124} 
>   0 = {int[18]@8127} 
>   1 = {java.lang.Class@2858} "class com.android.okhttp.internal.http.Http1xStream$FixedLengthSource"
>   2 = {java.lang.Class@2880} "class com.android.okhttp.okio.RealBufferedSource$1"
>   3 = {java.lang.Class@3793} "class java.io.BufferedInputStream"
>   4 = {java.lang.Class@3793} "class java.io.BufferedInputStream"
>   5 = {java.lang.Class@3793} "class java.io.BufferedInputStream"
>   6 = {java.lang.Class@6708} "class org.ksoap2.transport.HttpTransportSE"
>   7 = {java.lang.Class@6708} "class org.ksoap2.transport.HttpTransportSE"
>   8 = {java.lang.Class@6708} "class org.ksoap2.transport.HttpTransportSE"

Wireshark traces shows the responses are normal. 

This usually can be remedied by calling HttpTransportSE.getServiceConnection().disconnect() followed by HttpTransportSE.call() again.  
Could anyone shed some light on this?

**Comment by 8124** [comment]
thank you,, 
i have mistake for it in write, and that was probably has been broken file

**Comment by zheka2** [comment]
Have same error in AVD

**Comment by mosabua** [comment]
Unless you can provide more info on what might actually be wrong and maybe provide a PR with a fix there is nothing I can do here.
