### ISSUE TITLE
Isn't kSOAP2 a little too strict with unique IDs?

### ISSUE THREAD

**Issue by sarbogast** [simpligility/ksoap2-android#123]
kSOAP2 refuses to parse a SOAP response I'm getting because it contains 2 elements with the same id value.
The thing is that in the XML Schema, this id is of type anyURI, not xs:ID, so it doesn't have any unicity semantic:
https://github.com/oehf/ipf/blob/8a22c51a47fab1af6fea7da81f9e5d8de636e225/commons/ihe/xds/src/main/resources/wsdl/schema/ebRS30/rim.xsd#L103

Is that a bug in kSOAP2 or is there a way to disable that exception?

**Comment by mosabua** [comment]
Imho thats probably a bug in he schema... why would it be defined as an ID when it actually is not.
