### ISSUE TITLE
Last release doesn't contain okhttp module

### ISSUE THREAD

**Issue by Bwaim** [simpligility/ksoap2-android#125]
Is it planned to make a release containing the latest module added for okhttp ?

**Comment by mosabua** [comment]
yes .. just have to see what the current build failures are and potentially look at merging outstanding PRs.

**Comment by mosabua** [comment]
3.6.3 released. You can find the module in the repo now. 

https://oss.sonatype.org/content/repositories/ksoap2-android-releases/com/google/code/ksoap2-android/ksoap2-okhttp/

hope that helps

**Comment by Bwaim** [comment]
Thanks a lot !
