### ISSUE TITLE
Problems of HttpTransportSE.call not returning when server does

### ISSUE THREAD

**Issue by gabrielsqsf** [simpligility/ksoap2-android#126]
Good afternoon,

I have a problem with a very large request. When this request is sent to our webservice it only returns when timeout is reached. The server returns in about 20 minutes before timeout is received.

The communication works well with small requests, is there any issue with slow responses? (Around 10~15 minutes)

**Comment by mosabua** [comment]
Not from this framework... your overall impl however might have issues wit these timings.

**Comment by gabrielsqsf** [comment]
Good moning, @mosabua,

It unfortunatelly only happens with this framework, if i use any other framework, the same payload works well... Even with curl it works well. 

But you may be right about it being a problem with some other thing, as i only managed to test this vs other frameworks and curl on desktop and not on Mobile.

Any tips on what to look for?

**Comment by mosabua** [comment]
mobile has completely different processing power and network connection happening so you cant compare.. but essentially try it on a emulator or device with good network connection and see where it times out ... attach with a debugger and see what happens
