### ISSUE TITLE
HttpsTransportSE throws exception java.net.UnknownHostException: Unable to resolve host "my.host.com": No address associated with hostname

### ISSUE THREAD

**Issue by KapilThakur007** [simpligility/ksoap2-android#128]
Hi,
while using HttpsTransportSE() , it throws exception
"java.net.UnknownHostException: Unable to resolve host "my.host.com": No address associated with hostname" in Android PIE while working fine in other android versions and simple HttpTransportSE() is also working fine.

Please help how to resolve this.

**Comment by mosabua** [comment]
We can not debug your specific problem to you. Maybe the host is not exposed via https? Or really not available? Otherwise .. not sure ... maybe something in the network stack in Pie is getting in the way.

**Comment by Kisty** [comment]
Sounds like you're using HTTP rather than HTTPS which is disabled by default on Android Pie. You just need to specify the domains you're app is using or enable HTTPS on your server. See https://developer.android.com/about/versions/pie/android-9.0-changes-28#tls-enabled
