### ISSUE TITLE
How to use with OkHttp

### ISSUE THREAD

**Issue by matpag** [simpligility/ksoap2-android#130]
Hi,
i would use this library with OkHttp.

I use generated Soap classes from EasyWSDL and there is a way to override the default transport used.

The problem is:
If I use `OkHttpTransportSE`, i get a `java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/huc/OkHttpURLConnection;` if used with OkHttp 3.14.2, 
While I'm not able to use `OkHttpTransport` because it is not extending the `Transport` interface which is required by the generated classes.

Is there a way to solve this problem?
Thank you

**Comment by matpag** [comment]
The `java.lang.NoClassDefFoundError` is probably caused by using a too much updated `OkHttp` version. With 3.12.X is working

**Comment by Kisty** [comment]
@matpag Are you getting this crash with release or debug/development builds? If it's just release, then you might have a proguard/R8 shrinker issue. If not, can you post the output of `./gradlew app:dependencies` perhaps there's a mismatch of OkHttp libraries not using the same version

**Comment by matpag** [comment]
The `NoClassDefFoundError` is clear enough, ksoap2 is not compatible with okhttp 3.14.X (and i can survive with this currently).

The other problem is harder. 
I would expect `OkHttpTransport` to implement `Transport` and this is blocking for me because EasyWSDL generates methods like this:
```
protected org.ksoap2.transport.Transport createTransport() {
    try
    {
        java.net.URI uri = new java.net.URI(url);
        if (uri.getScheme().equalsIgnoreCase("https"))
        {
            int port=uri.getPort() > 0 ? uri.getPort() : 443;
            return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
        }
        else
        {
            return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
        }
    }
    catch (java.net.URISyntaxException e)
    {
    }
    return null;
}
```
and overriding this to use `OkHttpTransport` is not possible.

So i tried with `OkHttpTransportSE` but with this interceptors are not called (because internally it's not using the default request/response of okhttp)

**Comment by mosabua** [comment]
You might have to check with EasyWSDL authors what they suggest. And in terms of OKHTTP  .. we can maybe upgrade it. You wanna try sending a PR for that?

**Comment by matpag** [comment]
I don't have time currently, maybe in the next weeks I can take a look at it 👍

**Comment by robocik** [comment]
From my point of view, OkHttpTransport should be fixed in the way that it should extends org.ksoap2.transport.Transport (like the rest transport classes).  Then in EasyWSDL we can try to implement our features (which now are in AdvancedHttpTransportSE) in the new class which will extends OkHttpTransport

**Comment by mosabua** [comment]
I am more than happy to look at PRs and cut releases, but I dont have time to do the actual development..

**Comment by matpag** [comment]
The migration it's not easy. With OkHttp 3.14.X they removed the `OkHttpURLConnection` and a lot of the stuff around it, they dropped support to `HttpUrlConnection`.

Maybe this can be possible creating an adapter between the current `OkHttpClient` implementation and the `Transport` interface but it's not an easy task (at least for me).

A starting point could be to use this gist: https://gist.github.com/swankjesse/dd91c0a8854e1559b00f5fc9c7bfae70 provided by one of the OkHttp maintainers, but it's something deprecated and I don't know if it's worth it

**Comment by robocik** [comment]
As a temporary solution you can try to create a class which extends on your generated service class and override sendRequest method. The default implementation basically invoke a call method on Transport class but in your implementation you can skip using Transport object and use OkHttp to send Ksoap2 envelope.

**Comment by robocik** [comment]
I wanted to look at OkHttp implementation. I see that there is a ksoap2-okhttp module but how developers can use it in their applications? In ksoap2-android-assembly-3.6.4-jar-with-dependencies.jar this module is missing. So are classes from this okhttp module used by anyone? Because if not we can make some changes and improve them

**Comment by matpag** [comment]
When i tried to use the `ksoap2-okhttp` module in Android, i proceeded in this way:

add the maven repository in the project `build.gradle` file:

```
allprojects {
    google()
    jcenter()
    maven {
        url 'https://oss.sonatype.org/content/repositories/ksoap2-android-releases/'
    }
}
```

The in the app `build.gradle` i added the line to the specific module (which dinamically download all the needed ksoap2 dependencies)

```
dependencies {
    implementation "com.google.code.ksoap2-android:ksoap2-okhttp:3.6.4"
}
```
