### ISSUE TITLE
NoClassDefFoundError: org.ksoap2.serialization.SoapObject  API:19

### ISSUE THREAD

**Issue by iman2420** [simpligility/ksoap2-android#132]
Hi. i try to update library from **3.1.1 TO 3.6.4**. but i got **NoClassDefFoundError** in some devices on android version 4.4.
how to resolve this problem?

**Comment by robocik** [comment]
On some Android devices there is a builtin older version of ksoap2 which cause simillar problems. A few customer of EasyWSDL generator encouter this. We solve this problem by repackage a latest version of ksoap2 lib to another package name (using jarjar tool)

**Comment by iman2420** [comment]
So please send the correct .jar file to me

**Comment by robocik** [comment]
Give me your email address. I will send you

**Comment by iman2420** [comment]
plus.reflection@gmail.com

**Comment by robocik** [comment]
I've sent the file. I hope that gmail will allow you to download it

**Comment by iman2420** [comment]
But unfortunately I have not received any email from you.
You can upload the file in Dropbox and then send it the download link.
Many thanks

**Comment by robocik** [comment]
I have uploaded this file to my server. Here is the link. 
https://easywsdl.com/Content/Download/ksoap2-android-assembly-3.6.4-jar-with-dependencies-jarjar.jar
Please let me know when you download it so I will remove it

**Comment by iman2420** [comment]
I download it. Thank you so much...

**Comment by robocik** [comment]
Please let me know if this repackaged jar solves your problem

**Comment by krudos** [comment]
can you share the file again? i am having issues with android 4.4.4
thanks!
