### ISSUE TITLE
Outdated okhttp dependency

### ISSUE THREAD

**Issue by robocik** [simpligility/ksoap2-android#138]
In EasyWSDL, we have got info from our customer that Google PlayStore is reporting serious API violations, which is caused by an outdated okhttp3 library included into ksoap2 library. As a first try of solving this issue, I was tried to upgrade okhttp3 to version 3.14.9 but unfortunately this is not possible (I got compilation error) because some classes are missing in this version.
So maybe we should just remove entire code related with okhttp3 library because it is not supported anymore and can cause problems with releasing apps in Google PlayStore?

**Comment by Kisty** [comment]
What version of ksoap2 do you have? 
Did EasyWSDL give you the generated code and the version to use? 
Am unsure what API violations you have but I haven't noticed them in our apps. Can you give an example of the error?

**Comment by robocik** [comment]
easyWSDL is using the latest ksoap2 v3.6.4 which has a dependency to okhttp v3.12.1. Our customer reported to us problem in publishing his app to Google PlayStore. I have asked him to provide me details about problems reported by Google.
When I get it, I will provide more details

**Comment by mosabua** [comment]
If you are not using the okhttp code from the library you can just exclude that dependency

**Comment by robocik** [comment]
For now customer didn't provide me more detials so for now I close this issue. If needed we can always reopen it.
