### ISSUE TITLE
In any cases throw EOFException

### ISSUE THREAD

**Issue by rafaelpivetta** [simpligility/ksoap2-android#67]
Package version ksoap2-android-assembly-3.4.0-jar-with-dependencies.jar throw EOFException in any cases the invoke method call throw the EOFException.
It occurs in random cases for the same address, in the webserver log the request isn't registered.
I'm using S3 with android 4.3.

Does anyone know why this happens ?

...
transport.call("\"" + NAMESPACE + METHOD +"\"", envelope);
...

08-15 15:45:54.625: W/System.err(27006): java.io.EOFException
08-15 15:45:54.635: W/System.err(27006):  at libcore.io.Streams.readAsciiLine(Streams.java:203)
08-15 15:45:54.635: W/System.err(27006):  at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:579)
08-15 15:45:54.635: W/System.err(27006):  at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:827)
08-15 15:45:54.635: W/System.err(27006):  at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:283)
08-15 15:45:54.635: W/System.err(27006):  at ibcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
08-15 15:45:54.635: W/System.err(27006):  at org.ksoap2.transport.ServiceConnectionSE.getResponseCode(ServiceConnectionSE.java:103)
08-15 15:45:54.635: W/System.err(27006):  at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:192)
08-15 15:45:54.635: W/System.err(27006):  at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:118)
08-15 15:45:54.635: W/System.err(27006):  at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:113)

**Comment by mosabua** [comment]
It most likely is NOT random. You will have to figure out hwats going on but looking at the stack trace this is deeply embedded in the Android system (libcore...) and NOT in ksoap2 android so it it most likely not a bug with ksoap2-android but either your implmentation or Androids net stack or your server.

**Comment by rafaelpivetta** [comment]
It worked setting the header property "Connection".

ArrayList<HeaderProperty> headerPropertyArrayList = new ArrayList<HeaderProperty>();
headerPropertyArrayList.add(new HeaderProperty("Connection", "close"));
transport.call(SOAP_ACTION, envelope, headerPropertyArrayList);

https://code.google.com/p/ksoap2-android/issues/detail?id=173&can=1&start=100
Comment #1.
