### ISSUE TITLE
Unable to remove 'n0' prefix from body element

### ISSUE THREAD

**Issue by ChrisDolge** [simpligility/ksoap2-android#72]
Hi, 

1. Prepare a soap envelope 'envelope' with some soap header and body
2. set:
       envelope.dotNet = true;
       envelope.implicitTypes = true;
       envelope.setAddAdornments(false);
3. When checking the requestdump with httpTransportSE.debug  = true, 'n0' is prefixed with body element

any suggestion ? 

I work with the latest release 3.5.0 but it doesn't work.

If i use version 3.0.0-RC.4 it works.

**Comment by mosabua** [comment]
@ChrisDolge did you find a way to make it work? Why did you close the ticket otherwise?

**Comment by ChrisDolge** [comment]
Yes , it was a problem in my code.

**Comment by mosabua** [comment]
Great for the confirmation that this is not our bug ;-)
