### ISSUE TITLE
XmlPullParserException when parsing response from magento web service

### ISSUE THREAD

**Issue by mwshubham** [simpligility/ksoap2-android#76]
My web service works fine except from one of the website when i don't get response but i get this error

org.xmlpull.v1.XmlPullParserException: expected: '>' actual: '￿' (position:END_TAG @8:19 in java.io.InputStreamReader@41e579c8)

due to some character i am getting the exception.

I am using the ksoap2-android-assembly-3.0.0-jar-with-dependencies jar file.

**Comment by robocik** [comment]
Please put here entire http request/response. You can get it by using Fiddler application (http://www.telerik.com/fiddler)

**Comment by mosabua** [comment]
Agreed. With the little information you provided we can not reproduce the problem. Also it look more like a misconfiguration of the webservice using an invalid characterset or encoding or something along those lines.

**Comment by mosabua** [comment]
Closing now... feel free to reopen when you have more details.

**Comment by mwshubham** [comment]
please reopen this issue. I can understand that i was having very little information.

Also i am working on ubuntu and fiddler is kindoff not supported for me right now.
here is a stackoverflow question that i have created.
http://stackoverflow.com/questions/33921407/soap-messageprotected-looks-like-we-got-no-xml-document

**Comment by mwshubham** [comment]
I have not worked on the network debugging tools. So i am new to fiddler as well.

**Comment by mosabua** [comment]
From your stackoverflow message this is NOT related to ksoap2-android. Your webservice is crashing. You need to fix it.

**Comment by mwshubham** [comment]
Thank you sir, for your reply. You can now close this issue. BTW i am your big fan. You have done a excellent job. Thanks for replying on the SO post.

**Comment by mwshubham** [comment]
Hello sir i have putted response object as you said. I am getting "no" as a session id in which i am getting XmlPullparserException. Please have a look: http://stackoverflow.com/questions/33921407/soap-messageprotected-looks-like-we-got-no-xml-document
