### ISSUE TITLE
How to use HttpsTransportSE

### ISSUE THREAD

**Issue by jackson-therasoft** [simpligility/ksoap2-android#77]
I am following this link.
http://stackoverflow.com/questions/3440062/ksoap-2-android-with-https

It has an example to use HttpTransportSE.

HttpTransportSE aht = new HttpTransportSE(URL);    
aht.call(SOAP_ACTION, envelope);

Likewise,
Can you give me example with HttpsTransportSE ?
It has come with parameter like proxy, server etc.

I have to connect this URL

https://www.therasoftonline.com/tms/myhealthpro.asmx

Can you please help?

**Comment by robocik** [comment]
I would try something like that (I'm writing from the top of my head):

HttpsTransportSE  aht = new HttpsTransportSE ("www.therasoftonline.com",443,"tms/myhealthpro.asmx",10000);

Please try this. Probably in this sample could be small error but the main idea should be correct.

**Comment by mosabua** [comment]
More information is also available on the site as well as via the javadoc.
