### ISSUE TITLE
filter by ArrayOfString

### ISSUE THREAD

**Issue by thanhhuynhduy** [simpligility/ksoap2-android#78]
I'm using Magento API to make android app, but I don't know how to parse ArrayOfString in complex_filter.
Such as: I want to filter by category_ids or website_ids in http://devdocs.magento.com/guides/m1x/api/soap/catalog/catalogProduct/catalog_product.list.html. Please help me. Thanks.

**Comment by mosabua** [comment]
Not related to ksoap2-android as a library. Please check out the example code or ask on stackoverflow or the mailing list
