### ISSUE TITLE
java.io.IOException: HTTP request failed, HTTP status: 301  on calling webservices

### ISSUE THREAD

**Issue by ghost** [simpligility/ksoap2-android#79]
Is their any solution for Url Redirection issue by Ksoap api.
I am currently using ksoap2-android-assembly-3.0.0-jar-with-dependencies.jar

java.io.IOException: HTTP request failed, HTTP status: 301 
01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:195) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:116) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at org.ksoap2.transport.HttpTransportSE.call(HttpTransportSE.java:111) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at com.webkul.mobikul.Connection.SoapConnection.getDataFromServer(SoapConnection.java:115) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at com.webkul.mobikul.Connection.SoapConnection.doInBackground(SoapConnection.java:61) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at com.webkul.mobikul.Connection.SoapConnection.doInBackground(SoapConnection.java:21) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 01-21 20:11:09.555 32159-32232/com.webkul.mobikul W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by syshex** [comment]
As for following the redirect automatically, I don't believe so. Maybe someone on the list will reply with a more definitive answer.

As for the handling of that exception, I believe that a http code other than 200 will throw a HttpResponseException  (which extends from IOException) . 

That HttpResponseException has the method getStatusCode that returns the int http code that the server returned. This should allow for handling the problem inside the catch statement, depending on the server error code.

hope this helps

**Comment by mwshubham** [comment]
Thanks for the reply in a short period of time. But as I am using KSoap as a library I am not much informed about what is going behind the scene. It will take some time for me to understand your answer. But I will be thankful if I get either more definite or  a simpler answer.

**Comment by syshex** [comment]
A small example may help :

        try {
            ht.call(SERVER_SYNC_METHODNAME_ACTION, envelope);
            SoapObject received = (SoapObject) envelope.getResponse();

        } catch (SoapFault e) {
            throw e;
        } catch (HttpResponseException e) {
            if ( e.getStatusCode() == 301 ) {
                 //DO SOMETHING SPECIAL HERE
            } else
                throw e;
        } catch (IOException e) {
            throw e;
        } catch (XmlPullParserException e) {
            throw e;
        }

**Comment by mwshubham** [comment]
ok thanks for the explanation. There is a problem that the exception " java.io.IOException: HTTP request failed, HTTP status: 301" is not caught under "HttpResponseException" but goes into the IOException block. is it possible?

**Comment by robocik** [comment]
First of all I would advice you to use the latest version of ksoap2 library (v3.6 ) because HttpResponseException class has been introduced in version 3.5 so probably in your older version you don't have access to http response code (and to HttpResponseException). When you update ksoap2 library then you should be able to use solution mentionen by syshex

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
