### ISSUE TITLE
Gradle support

### ISSUE THREAD

**Issue by dipici** [simpligility/ksoap2-android#80]
Hi @simpligility,

I can not add this library to gradle.
compile 'com.google.code.ksoap2-android:ksoap2-android:3.6.0' 
when I sync i get this error: 
Error:(58, 13) Failed to resolve: com.google.code.ksoap2-android:ksoap2-android:3.6.0

> Could not resolve all dependencies for configuration ':app:_repositoriesCompile'.
   > Could not resolve com.google.code.ksoap2-android:ksoap2-android:3.6.0.
     Required by:
         SyntonaLogic:app:unspecified
      > Could not resolve com.google.code.ksoap2-android:ksoap2-android:3.6.0.
         > Could not get resource 'https://github.com/omadahealth/omada-nexus/raw/master/release/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
            > Could not GET 'https://github.com/omadahealth/omada-nexus/raw/master/release/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
               > peer not authenticated
      > Could not resolve com.google.code.ksoap2-android:ksoap2-android:3.6.0.
         > Could not get resource 'https://jcenter.bintray.com/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
               > peer not authenticated
      > Could not resolve com.google.code.ksoap2-android:ksoap2-android:3.6.0.
         > Could not get resource 'https://oss.sonatype.org/content/repositories/ksoap2-android-releases/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
            > Could not GET 'https://oss.sonatype.org/content/repositories/ksoap2-android-releases/com/google/code/ksoap2-android/ksoap2-android/3.6.0/ksoap2-android-3.6.0.pom'.
               > peer not authenticated

**Comment by mosabua** [comment]
THis should work just fine. All dependencies are avaiable in the sonatype repo. I am not sure what jcenter or your gralde configuration are breaking. You would have to provide more details. Until then I am closing this issue.
