### ISSUE TITLE
EOF Exception despite header property

### ISSUE THREAD

**Issue by wisien92** [simpligility/ksoap2-android#81]
Hi,

I am using v.3.6.0 and I still get 

> java.io.EOFException                                                                                   
> at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)                                                                                  >  at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
> ...

This is my code for sending soap (I am adding ("Connection", "close") header in createHttpHeaders):

    HttpTransportSE transport = new HttpTransportSE(url.toString(), TIMEOUT_VALUE));
    try {
        //transport.getServiceConnection().setRequestProperty("Connection", "close");
        transport.call(null, soapEnvelope, createHttpHeaders());

Are there more sollutions to this problem?

**Comment by mosabua** [comment]
You might want to try with the new okhttp transport as there are some underlying Android HTTP library problems.
