### ISSUE TITLE
ksoap2-android + OkHttp3 + Interceptors

### ISSUE THREAD

**Issue by adam-lincoln** [simpligility/ksoap2-android#84]
Hi all,

I have just been given the task of adding a retry interceptor to an Android app that uses ksoap2-android and the OkHttp3. 

For non-soap requests, I've added an interceptor to the OkHttp client and this has worked well for LTE/low bandwidth connections. However, the interceptor is not even called when the OkHttp client is passed into the ksoap2-android lib (in OkHttp3ServiceConnectionSE, line ~60).

I would love to contribute this functionality to the library but I'm not sure how. @mosabua I'm mentioning you as I hope you might be able point me in the right direction. I'm using both OkHttp3TransportSE and OkHttp3ServiceConnectionSE in my app.

Cheers,
Adam

**Comment by mosabua** [comment]
If you can implement it in the library and send a pull request I can check it out and merge it. And cut a new release..

**Comment by fuhoi** [comment]
Okay great - I'll give it a go!

**Comment by knaufinator** [comment]
I just ran into this issue as well, was trying to implement a retry mechanism with the interceptor.

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
