### ISSUE TITLE
java.io.IOException: BufferedInputStream is closed

### ISSUE THREAD

**Issue by ghost** [simpligility/ksoap2-android#86]
I have been using Ksoap2 library in my application from past 11 months. Since then i have started serious programming. 
From the day one in android development i am bit facing this every day or other **"java.io.IOException: BufferedInputStream is closed"** . There is much information available on the www. However i feel, the information is discrete and not much relevant.

By relevant means 
How come increasing timeout to to around 60000 will solve the problem.
How come putting the soap request in a infinite loop is the solution to the answer.

It will be very helpful if you help me out in sorting this problem, as my application is heavily depended on SOAP API. 
I just want information reading this context. **Why my buffered input stream is being closed? What checks, counter action should be taken in order to prevent and resolve it.**

Thanks

**Comment by mwshubham** [comment]
Similar thread: https://groups.google.com/forum/embed/#!topic/ksoap2-android/7BQIv80j-OU
non-standard timeout is not the solution for me

**Comment by ronaldoleitte1975** [comment]
Ho ghost, did you can solve this issue? I am also getting tis exception in my app.
Thank you

**Comment by mosabua** [comment]
No changes on this - closing as part of clean up.
