### ISSUE TITLE
MTOM ksoap2 Android

### ISSUE THREAD

**Issue by msajaynath** [simpligility/ksoap2-android#88]
i am getting below exception while accesing a WCF service using ksoap2 in android 
org.xmlpull.v1.XmlPullParserException: unexpected type (position:TEXT 
--uuid:095

Is this issue been taken care of in the new version 
I am still getting it.

**Comment by mosabua** [comment]
I dont know what this error is and with that little information I cant do anything either.

**Comment by msajaynath** [comment]
i am facing issue similar to this one https://github.com/csf033/ksoap2-android/issues/101

**Comment by mosabua** [comment]
I can not test this at all so you are going to have to provide more information and ideally even a fix by debugging the issue.

**Comment by msajaynath** [comment]
i have debugged the issue .It is not able to parse the GUID (UUID) send from wcf server.

We are sending the UUID in request after marshaling.But i couldn't find a way to do the same for response

**Comment by mosabua** [comment]
I have no access to a system that I could test this with. You will either have to come up with your own fix and contribute or ask on the mailing list for help from others and work together. I can merge any fixes and do a release but I have no resources to work on the issue itself.

**Comment by robocik** [comment]
This exception is not a bug, rather a missing feature. MTOM transfer uses different request/response format which is not compatible with ksoap2 and there is no single line of code in ksoap2 sources for parsing MTOM format.
In our [http://easywsdl.com](http://easywsdl.com) generator we have created MTOM implementation from scratch.
So to solve your problem your can turn off MTOM transfer in WCF service (this is possible if you are an author of this web service). Another option is to uses our generator which will handle all ksoap related stuff automatically.
If your need more info about this issue, let me know.

**Comment by msajaynath** [comment]
i am getting response in response dump .Is there any way i can edit the source code to address this issue.

**Comment by robocik** [comment]
you can easly download ksoap2 source code from [here](https://github.com/simpligility/ksoap2-android) and implement this feature. You can implement this for yourself or send your changes as a pull request to include them into a official release of ksoap2 lib.

**Comment by mosabua** [comment]
A pull request would be great of course ;-)
