### ISSUE TITLE
Can't see generated XML in Log

### ISSUE THREAD

**Issue by Luckygirlllll** [simpligility/ksoap2-android#98]
Hi, I'm using this code to see generated xml in the Log, but I see just empty string there.
```
httpTransport.debug = true;
httpTransport.call(SOAP_ACTION, envelope);
AppLog.e(httpTransport.requestDump);
AppLog.e(httpTransport.responseDump);
```
What I'm doing wrong? Why  generated xml don't display?

**Comment by mosabua** [comment]
You will have to debug this yourself and find out.
